name: geosmart-template
channels:
  - conda-forge
dependencies:
  - python=3.12
  - sphinxcontrib-bibtex
  - jupyter-book
  - jupytext
  - plotly
  - pandas
  - matplotlib
  - xarray
  - ipywidgets
  - netcdf4
  - s3fs
  - zarr



